"""
==============================================================================
Script:     hw02_profile.py
Purpose:    One-run data profile (EDA) of the transactions fact table:
            loads the data, prints 13 profiling checks, validates the
            expected shape, saves 3 charts, and writes a text summary.
Dataset:    data/raw/fact_transactions.csv
Author:     Emma Maguire (MIS3060 - Business Intelligence & AI, Villanova)
            Script generated with Claude (Anthropic)
Generated:  2026-09-23

How to run: open a terminal in the PROJECT ROOT folder (the folder that
            contains both "data" and "hw02") and run:
                python hw02/hw02_profile.py
            (or "python hw02_profile.py" if you saved it in the root)

Outputs:    hw02/charts/hist_amount.png
            hw02/charts/box_amount_by_type.png
            hw02/charts/scatter_shares_amount.png
            hw02/hw02_profile.txt
==============================================================================
"""

import os

import matplotlib
matplotlib.use("Agg")  # save charts to files without needing a display window
import matplotlib.pyplot as plt
import pandas as pd

# ------------------------------------------------------------------------------
# Settings
# ------------------------------------------------------------------------------
DATA_PATH = os.path.join("data", "raw", "fact_transactions.csv")
OUT_DIR = "hw02"
CHART_DIR = os.path.join(OUT_DIR, "charts")
SUMMARY_PATH = os.path.join(OUT_DIR, "hw02_profile.txt")
EXPECTED_SHAPE = (298772, 9)

# Show every column/row of small tables instead of "..." truncation
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

# Everything passed to report() is printed AND saved for the summary file
summary_lines = []


def report(text=""):
    """Print text to the terminal and keep a copy for hw02_profile.txt."""
    text = str(text)
    print(text)
    summary_lines.append(text)


def section(title):
    """Print a clear section header."""
    report("")
    report("=" * 70)
    report(title)
    report("=" * 70)


def find_col(df, keyword):
    """Find the ID column for a keyword (e.g. 'client' -> 'client_id')."""
    if f"{keyword}_id" in df.columns:
        return f"{keyword}_id"
    matches = [c for c in df.columns if keyword in c.lower()]
    return matches[0] if matches else None


# ------------------------------------------------------------------------------
# 1. Load the data
# ------------------------------------------------------------------------------
if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        f"Could not find {DATA_PATH}. Run this script from the project root "
        f"folder (current folder is: {os.getcwd()})"
    )

df = pd.read_csv(DATA_PATH)
df["txn_date"] = pd.to_datetime(df["txn_date"], errors="coerce")
print(f"Loaded {DATA_PATH}")

report("HW02 DATA PROFILE - fact_transactions.csv")
report(f"Generated by hw02_profile.py on {pd.Timestamp.now():%Y-%m-%d %H:%M}")

# ------------------------------------------------------------------------------
# 2. Shape
# ------------------------------------------------------------------------------
section("2. SHAPE (rows x columns)")
report(f"{df.shape[0]:,} rows x {df.shape[1]} columns")

# ------------------------------------------------------------------------------
# 3. Column names and data types
# ------------------------------------------------------------------------------
section("3. COLUMN NAMES AND DATA TYPES")
report(df.dtypes.to_string())

# ------------------------------------------------------------------------------
# 4. Missing values per column
# ------------------------------------------------------------------------------
section("4. MISSING VALUES PER COLUMN")
report(df.isna().sum().to_string())
report(f"Total missing cells: {int(df.isna().sum().sum()):,}")

# ------------------------------------------------------------------------------
# 5. Descriptive statistics for numeric columns
# ------------------------------------------------------------------------------
section("5. DESCRIPTIVE STATISTICS (numeric columns)")
report(df.describe().round(2).to_string())

# ------------------------------------------------------------------------------
# 6. txn_type value counts and percentages
# ------------------------------------------------------------------------------
section("6. TXN_TYPE VALUE COUNTS")
type_counts = pd.DataFrame({
    "count": df["txn_type"].value_counts(),
    "percent": (df["txn_type"].value_counts(normalize=True) * 100).round(2),
})  # value_counts() is already sorted most -> least frequent
report(type_counts.to_string())

# ------------------------------------------------------------------------------
# 7. Unique clients, advisors, securities
# ------------------------------------------------------------------------------
section("7. UNIQUE CLIENTS, ADVISORS, SECURITIES")
for label in ["client", "advisor", "security"]:
    col = find_col(df, label)
    if col:
        report(f"Unique {label} IDs ({col}): {df[col].nunique():,}")
    else:
        report(f"Unique {label} IDs: no matching column found")

# ------------------------------------------------------------------------------
# 8. Date range
# ------------------------------------------------------------------------------
section("8. DATE RANGE (txn_date)")
report(f"Earliest txn_date: {df['txn_date'].min():%Y-%m-%d}")
report(f"Latest txn_date:   {df['txn_date'].max():%Y-%m-%d}")
bad_dates = int(df["txn_date"].isna().sum())
if bad_dates:
    report(f"Note: {bad_dates:,} txn_date values were missing or unreadable")

# ------------------------------------------------------------------------------
# 9. Duplicate txn_id check
# ------------------------------------------------------------------------------
section("9. DUPLICATE TXN_ID CHECK")
dup_count = int(df["txn_id"].duplicated().sum())
report(f"Duplicate txn_id rows: {dup_count:,}")

# ------------------------------------------------------------------------------
# 10. Amount: mean, median, skewness
# ------------------------------------------------------------------------------
section("10. AMOUNT - MEAN, MEDIAN, SKEWNESS")
amt_mean = df["amount"].mean()
amt_median = df["amount"].median()
amt_skew = df["amount"].skew()
report(f"Mean:     {amt_mean:,.2f}")
report(f"Median:   {amt_median:,.2f}")
report(f"Skewness: {amt_skew:.2f}")

# ------------------------------------------------------------------------------
# 11. Amount by txn_type
# ------------------------------------------------------------------------------
section("11. AMOUNT BY TXN_TYPE (sorted by mean, descending)")
by_type = (
    df.groupby("txn_type")["amount"]
    .agg(count="count", mean_amount="mean", median_amount="median")
    .round(2)
    .sort_values("mean_amount", ascending=False)
)
report(by_type.to_string())

# ------------------------------------------------------------------------------
# 12. Correlation matrix + three strongest correlations
# ------------------------------------------------------------------------------
section("12. CORRELATION MATRIX (shares, price, amount)")
corr = df[["shares", "price", "amount"]].corr().round(2)
report(corr.to_string())

# Collect each pair once (skip a variable with itself), rank by strength
pairs = []
cols = list(corr.columns)
for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        pairs.append((cols[i], cols[j], corr.iloc[i, j]))
pairs.sort(key=lambda p: abs(p[2]), reverse=True)

report("")
report("Three strongest correlations (ranked by absolute value):")
for rank, (a, b, r) in enumerate(pairs[:3], start=1):
    report(f"  {rank}. {a} vs {b}: r = {r:.2f}")

# ------------------------------------------------------------------------------
# 13. Negative shares by txn_type
# ------------------------------------------------------------------------------
section("13. SHARES - MIN, MAX, NEGATIVE COUNT BY TXN_TYPE")
shares_by_type = df.groupby("txn_type")["shares"].agg(
    min_shares="min",
    max_shares="max",
    negative_count=lambda s: int((s < 0).sum()),
)
report(shares_by_type.to_string())
report(f"Total negative shares values: {int((df['shares'] < 0).sum()):,}")

# ------------------------------------------------------------------------------
# 14. Shape validation
# ------------------------------------------------------------------------------
section("14. SHAPE VALIDATION")
if df.shape != EXPECTED_SHAPE:
    report(f"WARNING: shape is {df.shape}, expected {EXPECTED_SHAPE}!")
else:
    report(f"OK: shape matches expected {EXPECTED_SHAPE}")

# ------------------------------------------------------------------------------
# 15. Charts
# ------------------------------------------------------------------------------
os.makedirs(CHART_DIR, exist_ok=True)

# 15a. Histogram of amount with mean and median lines
fig, ax = plt.subplots(figsize=(10, 6))
ax.hist(df["amount"].dropna(), bins=100, color="steelblue", edgecolor="white")
ax.axvline(amt_mean, color="red", linestyle="--", linewidth=2,
           label=f"Mean = {amt_mean:,.2f}")
ax.axvline(amt_median, color="green", linestyle="-", linewidth=2,
           label=f"Median = {amt_median:,.2f}")
ax.set_title("Distribution of Transaction Amount")
ax.set_xlabel("Amount")
ax.set_ylabel("Number of Transactions")
ax.legend()
fig.tight_layout()
fig.savefig(os.path.join(CHART_DIR, "hist_amount.png"), dpi=150)
plt.close(fig)

# 15b. Horizontal box plot of amount by txn_type
types = by_type.index.tolist()  # same order as item 11 (highest mean first)
box_data = [df.loc[df["txn_type"] == t, "amount"].dropna() for t in types]
fig, ax = plt.subplots(figsize=(10, 6))
try:
    ax.boxplot(box_data, orientation="horizontal", tick_labels=types)  # newer matplotlib
except TypeError:
    ax.boxplot(box_data, vert=False, labels=types)  # older matplotlib
ax.set_title("Transaction Amount by Transaction Type")
ax.set_xlabel("Amount")
ax.set_ylabel("Transaction Type")
fig.tight_layout()
fig.savefig(os.path.join(CHART_DIR, "box_amount_by_type.png"), dpi=150)
plt.close(fig)

# 15c. Scatter of shares vs amount, colored by txn_type
fig, ax = plt.subplots(figsize=(10, 6))
colors = plt.get_cmap("tab10")
for i, t in enumerate(types):
    subset = df[df["txn_type"] == t]
    ax.scatter(subset["shares"], subset["amount"], s=4, alpha=0.4,
               color=colors(i % 10), label=t)
ax.set_title("Shares vs. Amount by Transaction Type")
ax.set_xlabel("Shares")
ax.set_ylabel("Amount")
ax.legend(title="txn_type", markerscale=4)
fig.tight_layout()
fig.savefig(os.path.join(CHART_DIR, "scatter_shares_amount.png"), dpi=150)
plt.close(fig)

print("")
print(f"Charts saved to {CHART_DIR}/")

# ------------------------------------------------------------------------------
# 16. Save the plain-text summary (items 2-13, plus the shape check)
# ------------------------------------------------------------------------------
with open(SUMMARY_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(summary_lines) + "\n")
print(f"Summary saved to {SUMMARY_PATH}")
print("Done.")